import { Navigate, Link, NavLink, useLocation } from 'react-router-dom'; import { motion } from 'framer-motion'; import { useApp } from '../context/AppContext.jsx';
export function ProtectedRoute({ children, admin = false }) { const { user } = useApp(); const location = useLocation(); if (!user) return <Navigate to="/login" state={{ from: location }} replace />; if (admin && user.role !== 'admin') return <Navigate to="/" replace />; return children; }
export function Reveal({ children, className = '' }) { return <motion.div className={className} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .38 }}>{children}</motion.div>; }
export function RatingStars({ value = 0, small = false }) { return <span className={`rating ${small ? 'small' : ''}`} aria-label={`${value.toFixed?.(1) || value} de 5 estrellas`}>{[1, 2, 3, 4, 5].map(n => <i key={n} className={`bi bi-star${n <= Math.round(value) ? '-fill' : ''}`} />)}</span>; }
export function QuantitySelector({ value, onChange, disabled = false }) { return <div className="quantity" aria-label="Cantidad"><button disabled={disabled || value <= 1} onClick={() => onChange(value - 1)} aria-label="Disminuir cantidad">−</button><span>{value}</span><button disabled={disabled} onClick={() => onChange(value + 1)} aria-label="Aumentar cantidad">+</button></div>; }
export function Empty({ icon = 'inbox', children, action }) { return <div className="empty-state"><i className={`bi bi-${icon}`} /><p>{children}</p>{action}</div>; }
export function Loading() { return <div className="text-center py-5"><div className="spinner-border accent-spinner" role="status"><span className="visually-hidden">Cargando</span></div></div>; }
export function Footer() { return <footer className="footer mt-auto"><div className="container d-flex flex-column flex-sm-row justify-content-between gap-2"><span>© {new Date().getFullYear()} Arte Mabel</span><span>Repostería artesanal hecha con cariño.</span></div></footer>; }
export function WhatsAppButton({ message }) { const number = import.meta.env.VITE_WHATSAPP_NUMBER; if (!number) return null; return <a className="whatsapp-button" href={`https://wa.me/${number}?text=${encodeURIComponent(message || 'Hola, quisiera información sobre sus productos.')}`} target="_blank" rel="noreferrer" aria-label="Contactar por WhatsApp"><i className="bi bi-whatsapp" /></a>; }
export function Navbar() { const { user, cart, logout, t, theme, setTheme, language, setLanguage } = useApp(); const count = cart.items.reduce((n, i) => n + i.quantity, 0); const nav = [['/', 'house', t.home], ['/catalog', 'grid', t.catalog], ['/favorites', 'heart', t.favorites], ['/orders', 'receipt', t.orders]]; return <nav className="navbar navbar-expand-lg sticky-top app-nav"><div className="container"><Link className="navbar-brand" to="/">ARTE <span>MABEL</span></Link><button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav"><i className="bi bi-list" /></button><div className="collapse navbar-collapse" id="main-nav"><div className="navbar-nav nav-center">{nav.map(([to, icon, label]) => <NavLink key={to} className="nav-link" to={to}><i className={`bi bi-${icon}`} />{label}</NavLink>)}</div><div className="navbar-nav nav-actions align-items-lg-center"><div className="dropdown"><button className="nav-icon" data-bs-toggle="dropdown" aria-label="Accesibilidad"><i className="bi bi-universal-access" /></button><div className="dropdown-menu dropdown-menu-end access-menu"><span className="dropdown-header">Apariencia</span><button className="dropdown-item" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}><i className={`bi bi-${theme === 'light' ? 'moon' : 'sun'}`} /> {theme === 'light' ? 'Oscuro' : 'Claro'}</button><span className="dropdown-header">Idioma</span><button className="dropdown-item" onClick={() => setLanguage(language === 'es' ? 'en' : 'es')}><i className="bi bi-translate" /> {language === 'es' ? 'English' : 'Español'}</button></div></div>{user ? <div className="dropdown"><button className="nav-icon" data-bs-toggle="dropdown" aria-label="Perfil"><i className="bi bi-person" /></button><div className="dropdown-menu dropdown-menu-end"><span className="dropdown-header">{user.name}</span>{user.role === 'admin' && <Link className="dropdown-item" to="/admin">Administración</Link>}<button className="dropdown-item" onClick={logout}>Cerrar sesión</button></div></div> : <Link className="nav-icon" to="/login" aria-label={t.login}><i className="bi bi-person" /></Link>}<Link className="nav-icon cart-link" to="/cart" aria-label={t.cart}><i className="bi bi-cart3" />{count > 0 && <span>{count}</span>}</Link></div></div></div></nav>; }
